services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.fast
      args:
        DOCKER_BUILDKIT: 1
    container_name: hack-the-ice-frontend
    restart: unless-stopped
    ports:
      - "8079:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=https://lena.linkpc.net
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
